### ISSUE TITLE
A sold-out ticket still looks available in the Explorer deck

### ISSUE THREAD

**Issue by sethogieva** [Mingla-LLC/mingla-main#2246]
Found during the #2242 investigation — [INVESTIGATE comment](https://github.com/Mingla-LLC/mingla-main/issues/2242#issuecomment-5329180229), finding D-2. Pre-existing and independent of #2242, filed now for a specific reason given below.

## What a user sees

On the **deck** route in the Explorer app, a sold-out ticket tier still renders as available — it shows a count of tickets remaining and lets the buyer add it to the cart. The sale is only rejected server-side, after they have committed to buying.

## Why it happens

`app-mobile/src/services/publicEventTicketsService.ts:48` puts `quantity_total` into a field named `capacity`. Both the shared contract and `TicketCartSheet`'s own availability gates read `capacity` as **remaining**, not as the total ever minted. So a tier with every seat sold still reports its full original count as available.

## Why file it now rather than later

Fixing #2242 switches the cold link route onto the canonical checkout bundle, which carries true remaining counts. The deck route keeps the legacy read. The two routes will then visibly disagree about the same tier — and if this is discovered afterwards it will read as a regression introduced by #2242, when in fact it is this pre-existing defect becoming visible by contrast. Registering it now keeps that attribution straight.

## Done means

One definition of "available" across both routes, with the field name matching what it holds, and a sold-out tier that cannot be added to the cart on either route.

Affected Surfaces: [iOS-consumer, Android-consumer] — shared service and sheet; observed on iOS. Surfaces explicitly NOT in scope: buyer-web (separate read path), business apps (not buyer surfaces), admin-web (no buyer flow).
