### ISSUE TITLE
Hosts see zero orders and sold after guests receive free tickets

### ISSUE THREAD

**Issue by sethogieva** [Mingla-LLC/mingla-main#2411]
## Customer impact

Guests successfully obtained free tickets, but the organiser-facing Host app showed **0 orders**, **0 sold**, and **Couldn't load** states for the same event. The contradiction appeared in three places: the Upcoming event list on Home, the Hub events list, and the published Edit Event page. Organisers therefore cannot trust attendance/order reporting even though checkout has created real tickets.

The organiser was told to complete every event detail and connect a bank account as a possible workaround. That must not be required to count free tickets: free-order reporting should work independently of payout onboarding.

## Required investigation

Prove where the read path loses or rejects real free-ticket orders. Reconcile the complete chain from checkout order/ticket writes through production schema/RLS/RPCs, Host summary/detail queries, cache/state, and all three UI error/zero states. Determine whether the shared symptom is one failed aggregate/query contract, an authorization/RLS mismatch, a response-shape/currency assumption, or multiple independent defects; do not infer bank setup as the cause without evidence.

The investigation must distinguish:

- a truthful zero from a failed read rendered as zero;
- order count from ticket quantity sold;
- free orders from paid/payout-dependent data;
- list summary queries from Edit Event detail/order queries;
- data that exists in production from stale/missing client cache.

## Affected surfaces

Affected Surfaces: `[business-iOS, business-Android, business-web-preview, buyer-web]` — Host Home/Upcoming, Hub, and Edit Event consume order/sold aggregates; buyer web is the upstream writer whose successful free-ticket issuance must reconcile with Host reads.

Surfaces explicitly NOT in scope: `[consumer-iOS, consumer-Android]` — no organiser reporting UI; `[admin-web]` — inspect only if it is an independent truth source, but no reported customer symptom there.

Classification: `bug`, `data-integrity`, `regression`; severity `S1-high`.

**Comment by sethogieva** [comment]
## INVESTIGATION — valid free orders crash the Host order mapper

**Mode:** INVESTIGATE only  
**Issue:** #2411  
**Production event:** `3014ea7e-f3e0-40d0-b112-a51f4e37e964` (“We Go Again Exhibition”)  
**Brand:** `ca6926ad-6dd7-4e3e-871d-3168d9031179`  
**Branch truth inspected:** fresh `origin/main` at `c8f27b4aee706f7cc69dc98825ac588ca187aab3`  
**Conclusion:** **PROVEN.** Production has 3 real orders and 6 valid tickets. The live Host reader receives them, then throws `TypeError: Cannot read properties of null (reading 'trim')` because `eventOrdersService` falsely types and treats the intentionally nullable currency on a zero-money order as a string. React Query consequently has an error and no data; downstream Host surfaces substitute `[]`, producing numeric zeroes and “Unable to load” / “Couldn't load orders.” A bank account is not required for free checkout or free-order reporting and was not the missing ingredient.

### Symptom summary

Expected: the organiser sees **3 orders** and **6 sold/admissions** for the event; free orders display no invented money currency. Actual: Home Upcoming and Hub show load-failure/zero-derived sales state, the event dashboard/edit flow calculates zero sold, and the Orders page says it could not load. The buyer-side write succeeded; the organiser-side read mapper failed.

“Orders” and “sold” are not interchangeable here:

- **3 orders** = three completed buyer checkout records.
- **6 sold** = sum of four line-item quantities (`1 + 4 + 1`) after refunds.
- **6 tickets/passes** = six valid ticket rows, each with one selected event-date row.

### Investigation manifest

Read in order: `AGENTS.md`; `COMMS.md` (including active public-release hold COMMS-0147); the complete #2411 issue; complete #2396 and every comment; merged PR #2402; prior currency/free-publish/order/analytics issues including #962, #1014, #2136, #2150, #2160, #855 and #874; canonical `mingla-forensics` skill, parity adapter and relevant memory; `README.md` Architecture Constitution; `docs/INVARIANT_REGISTRY.md`; the full chronological migration chain and migration tests around orders, free publish and checkout finalization; all `fetchEventOrders` callers and their UI consumers; deployed Host HTML and current web chunks; production schema, migration ledger, policies, brand/event/order/line/ticket/refund data, and owner-context RLS, all through read-only probes. No product files, production rows, bank state, orders, deployments or OTAs were changed.

### Q-scorecard

**Q1 — Do orders and tickets actually exist in production?**  
**Verdict: Yes — proven.** Three paid-status free orders, four line rows totaling six, six valid tickets and six ticket-date assignments exist.

**Q2 — Is “0” a truthful aggregate?**  
**Verdict: No — proven.** It is a failed read converted to an empty array/zero by client fallbacks. Canonical server truth is 3 orders / 6 sold.

**Q3 — What exact operation fails?**  
**Verdict: Proven.** PostgREST returns HTTP 200; the current deployed Host mapper executes `t.currency.trim()` when `t.currency` is `null`, throwing before any order maps.

**Q4 — Did missing bank/payout setup prevent free publishing, checkout or reporting?**  
**Verdict: No — ruled out.** This brand has no bank/provider account and no currency, yet its public scheduled event produced all valid order/ticket records. Null currency is the documented, schema-valid state for zero money.

**Q5 — Did RLS or brand membership hide the data?**  
**Verdict: No — ruled out.** Under Korede’s actual authenticated owner UID, RLS can read all 3 orders, 4 lines, 6 tickets and 6 ticket dates.

**Q6 — Is this a missing PostgREST relationship, schema-cache failure, payment-status filter or stale cache?**  
**Verdict: No — ruled out.** The exact nested select succeeds; all needed FKs/relations resolve; all 3 orders are in the live `paid` status; refreshing deterministically replays the same mapper exception.

**Q7 — Why do all three reported Host surfaces agree?**  
**Verdict: Proven.** Home, Hub/EventListCard, the event dashboard/editor and Orders page share `fetchEventOrders` through `useEventOrders` / `useEventSalesSummaries`. They differ only in how visibly they mask the same rejected query.

**Q8 — Is #2396/#2402 the same fix?**  
**Verdict: No — proven related contract drift, not the same path.** #2402 made the publish-response **event** mapper null-safe. #2411 is the separate **order** mapper, whose false `currency: string` declaration and `.trim()` remained live.

### Findings — six-field evidence

#### F-1 — Nullable free-order currency crashes the shared order mapper

1. **Symptom:** Real free tickets exist, but every Host consumer of event orders receives no mapped orders and enters an error/empty state.
2. **Layer:** Schema + production data + deployed runtime + source.
3. **Probe:** (a) execute the exact `.from("orders").select(...)` from `fetchEventOrders` against production; (b) replay the returned JSON with `rows.map(order => order.currency.trim())`; (c) download `https://host.usemingla.com` and its declared `__common-be6c49311532661acbb2357c9e15183c.js?v=orch1091`, then inspect the mapper around `.currency.trim()`.
4. **Evidence:** PostgREST returned HTTP 200 with 3 rows. Sanitized truth: `orders=3, paid_orders=3, line_rows=4, sold_quantity=6, order_total_values=[0], order_currency_values=[null], tickets=6, valid=6`. Replay output was exactly: `TypeError: Cannot read properties of null (reading 'trim')` and `rows=3, first_currency=null`. Source at `mingla-business/src/services/eventOrdersService.ts:45` declares `currency: string`; lines 160–216 issue the nested query; line 220 uses `as unknown as OrderRow[]`; line 224 executes `const orderCurrency = order.currency.trim();`. The current deployed Host web chunk contains the same live expression: `const a=(t.refunds??[]).filter(...),u=t.currency.trim(),c={},s={};`.
5. **Mechanism:** #1014 made zero-total order currency intentionally nullable, and the checkout finalizer correctly persists the session’s null currency. The stale client-only non-null contract bypasses generated typing, so the first valid free order aborts the entire map; no order reaches any aggregate or detail consumer.
6. **Severity:** **CONFIRMED ROOT CAUSE**.

#### F-2 — Summary surfaces convert a rejected read into numeric zero

1. **Symptom:** Home Upcoming and Hub can show zero-derived progress/count state alongside “Unable to load,” contradicting the six admissions in the database.
2. **Layer:** Hook + summary utility + UI.
3. **Probe:** Trace all `fetchEventOrders` call sites; inspect `useEventSalesSummaries` and `buildEventSalesSummary`; verify the corresponding implementation in the deployed common chunk.
4. **Evidence:** `mingla-business/src/hooks/useEventOrders.ts:151-160` passes `orders: query?.data ?? []` and `hasError: query?.isError ?? false`. `src/utils/eventSalesSummary.ts:91-103` returns `soldCount: 0`, `onlineRevenue: 0`, `soldLabel: "Unable to load"`, `revenueLabel: "Unable to load"` whenever `hasError`. The deployed chunk contains that exact branch. Home builds these summaries for live/upcoming offerings; `EventListCard.tsx:127-140` repeats the same shared query/summary flow for Hub.
5. **Mechanism:** React Query correctly marks the mapper exception as an error. The display contract then fabricates a numeric zero instead of preserving “unknown/error,” so count/progress consumers behave as if nothing sold even while labels admit the load failed.
6. **Severity:** **SECONDARY ROOT CAUSE**.

#### F-3 — Editor reconciliation silently drops the same error and becomes blind to sold tickets

1. **Symptom:** The published editor computes zero sold and can present client-side edit affordances as though no buyer commitments exist.
2. **Layer:** Hook + editor/buyer-protection context.
3. **Probe:** Trace the EditPublishedScreen sold-count source through `useEventReconciliation` to `useEventOrders` and `buildSoldCountContextFromOrders`.
4. **Evidence:** `src/hooks/useEventOrders.ts:109-112` returns only `ordersQuery.data ?? []` and discards `isError`. `src/components/event/EditPublishedScreen.tsx:471-482` builds sold-count context from that array. Its own comment says this live order context is supposed to keep buyer-protection edit guards from being blind; the rejected query turns it back into an empty context. Server RPC guards remain a backstop.
5. **Mechanism:** The same primary mapping exception is silently collapsed to `[]` before the editor can distinguish “zero sales” from “orders failed to load.” The UI’s preflight knowledge is therefore wrong even though server-side mutation guards can still reject protected edits.
6. **Severity:** **SECONDARY ROOT CAUSE**.

#### F-4 — Bank, payout onboarding and event-detail completeness are not causes

1. **Symptom:** The organiser was advised to fill all details/connect a bank, but reporting still failed.
2. **Layer:** Docs/invariants + schema + production data.
3. **Probe:** Read brand/event/payment fields and the #1014 active invariant; reconcile them with successfully finalized orders and tickets.
4. **Evidence:** Production brand: `default_currency=null`, `has_stripe_account=false`, `stripe_charges_enabled=false`, `stripe_payouts_enabled=false`, `has_paystack_subaccount=false`. Event: `status=scheduled`, `visibility=public`, `currency=null`. Nevertheless, production contains 3 paid-status orders and 6 valid tickets. `I-1014-FREE-PUBLISH-NO-PAYMENT-SETUP` explicitly requires free-only publication without payment setup and preserves null event currency. The schema check is `total_cents = 0 OR currency IS NOT NULL`; all affected orders have `total_cents=0`.
5. **Mechanism:** Payment setup establishes a currency for money-bearing transitions; it is deliberately irrelevant to a zero-money checkout. Adding a bank might influence future money-bearing state, but it cannot change or repair the already-valid null-currency order rows that crash this mapper.
6. **Severity:** **RULED OUT**.

#### F-5 — RLS/security authorization is correct for Korede’s owner context

1. **Symptom:** A permissions failure could superficially explain an empty organiser list.
2. **Layer:** Production schema/RLS/security.
3. **Probe:** In a read-only transaction, `SET LOCAL ROLE authenticated`, set `request.jwt.claim.sub` to Korede’s actual UID, and count the event’s orders, lines, tickets and ticket-date rows; inspect SELECT grants/policies and their brand-team predicates.
4. **Evidence:** Owner-context output: `{"orders":3,"line_items":4,"tickets":6,"ticket_days":6,"can_read_all_orders":true}`. Relevant tables have authenticated SELECT grants and enabled RLS. Orders and line items use the buyer-or-brand-team order predicate; tickets and ticket dates permit the buyer or event brand team. The user is an active `brand_owner`. The exact nested service-role PostgREST query also returns HTTP 200. No cross-brand row or unauthorized response was observed.
5. **Mechanism:** Authorization admits the rows. The loss happens only after the response reaches JavaScript, so changing membership or weakening RLS would not address the failure and would create needless exposure risk.
6. **Severity:** **RULED OUT**.

#### F-6 — PostgREST relationships, payment status, and cache are non-causes

1. **Symptom:** “Couldn't load” can also arise from a malformed nested select, status exclusion or stale cached zero.
2. **Layer:** Production API + schema + client cache.
3. **Probe:** Execute the exact nested select, inspect live FK relationship resolution and status values, and replay the mapper from a fresh saved response outside React Query.
4. **Evidence:** Exact query: HTTP 200, 3 rows, nested `events`, `tickets.ticket_event_dates`, `order_line_items.ticket_types`, `refunds.refund_line_items`; zero refunds. All 3 orders have `payment_status='paid'`, the status included by canonical sold aggregation. A fresh response replay immediately throws on null `.trim()`. `useEventOrders` stale time is only 15 seconds; retrying cannot alter a deterministic exception in unchanged rows.
5. **Mechanism:** Network/schema retrieval is successful and the live statuses are eligible. Cache merely stores the query error lifecycle; it does not create the null and cannot turn the rejected mapper into six orders.
6. **Severity:** **RULED OUT**.

#### F-7 — Unsafe row casting and an unrepresentative “free order” test allowed the contract drift

1. **Symptom:** The database intentionally allows null currency, but TypeScript and regression tests did not warn when the read path assumed a string.
2. **Layer:** Static analysis + tests.
3. **Probe:** Inspect mapper typing/casts and the event order service test fixtures; compare with generated/schema nullability and #1014 migration tests.
4. **Evidence:** `eventOrdersService.ts:220` forces Supabase data through `as unknown as OrderRow[]`; `OrderRow.currency` is `string`. The “free” service-test record inherits `currency: "GBP"` and tests already-mapped helpers, not `fetchEventOrders` against raw `{currency:null,total_cents:0}` data. #1014 tests prove the DB null contract but do not exercise this Host mapper. Git blame shows `.trim()` predates #1014; the schema changed later without this client type/path changing.
5. **Mechanism:** The unsafe cast suppresses the nullable database contract at the boundary, and the test fixture calls a currency-bearing record “free.” That combination let the cross-layer drift compile and ship.
6. **Severity:** **SUSPECTED CONTRIBUTOR**.

### Five-Truth-Layer reconciliation

| Truth layer | Proven state | Contradiction |
|---|---|---|
| Product/docs truth | Free-only offerings require no bank or currency; null means no currency, never implied GBP/USD. | The advice to add a bank contradicted the active #1014/#962 contracts. |
| Schema/migration truth | `orders.currency` is nullable; check permits null only when `total_cents=0`; production has #1014 and #2160 applied. | Client declares the same column non-null. |
| Writer/runtime truth | Latest checkout finalizer writes `v_session.currency`; free method/status paths finalize zero-total sessions and create lines/tickets/date assignments. | None in the writer: production output matches this contract. |
| Production data truth | 3 paid-status orders, 4 lines totaling 6, 6 valid tickets, all zero-total/null-currency. | Host numeric zero contradicts canonical rows. |
| Reader/UI truth | Deployed Host runs `.currency.trim()`, query rejects, consumers substitute `[]`; labels/errors and zero contexts fan out. | UI treats “unknown because read failed” as zero. |

The singular cross-layer break is the Host order-reader contract. The summary/editor masking broadens its impact.

### Migration-currentness and deployed-runtime proof

- Live `supabase_migrations.schema_migrations` contains both `20270108001014` and `20270420002160`.
- Live `information_schema.columns` says `public.orders.currency IS_NULLABLE='YES'`.
- Live constraint: `CHECK (((total_cents = 0) OR (currency IS NOT NULL)))`.
- Repository chronology: baseline made currency required; #1014 is the only intentional `DROP NOT NULL`; the last writer of `issue_1930_ticket_checkout_finalize_base` is #2160.
- The live finalizer definition has identity args matching #2160, MD5 `727e69af1fd1f04dca28395d49db0355`, and contains `v_session.currency`, the free method branch and `ticket_event_dates` writes.
- `https://host.usemingla.com` currently advertises `?v=orch1091`; its current common chunk hash is `be6c49311532661acbb2357c9e15183c`, and that deployed artifact contains both the null-unsafe mapper and the error-to-zero summary branch. This defect is not merely present on the investigation branch.
- #2396/#2402 changed `eventFromPublishResponse` for nullable **event** currency. It does not touch this deployed **order** mapper.

### Reproduction evidence

**Reproduced against current production data and current deployed Host code without mutating customer state.** The exact production PostgREST response was saved locally with credentials excluded, then passed into the exact deployed mapper expression. It failed on row 1 with `TypeError: Cannot read properties of null (reading 'trim')`. Separately, the current deployed Host common chunk was inspected and contains the same expression. A signed-in visual UI replay was not needed to establish causality and was not attempted against the customer account; no device/port from #2396 or another session was touched.

No Sentry email matched `Cannot read properties of null` / `reading trim` in the last seven days. That is consistent with React Query catching the rejected promise and the UI rendering a handled error rather than producing a global crash. It is also an observability blind spot: a severe organiser data-read failure can remain invisible to crash alerting.

### Blast radius — seven surfaces

| Surface | Coverage / impact |
|---|---|
| 1. Consumer iOS | **Not directly affected.** No organiser event-order reporting UI; buyer checkout writer succeeded. |
| 2. Consumer Android | **Not directly affected.** Same reason. |
| 3. Buyer/anonymous web | **Upstream writer in scope, not failing reader.** It successfully finalized these free orders/tickets; no bank dependency. |
| 4. Business iOS | **Affected.** Shared `fetchEventOrders` powers Home summaries, Hub cards, event dashboard, Orders, guest/reconciliation/editor contexts. |
| 5. Business Android | **Affected.** Same shared React Native service/hooks and consumers. |
| 6. Admin web | **Not affected by this code path.** Independent surface; no evidence its own reporting is wrong. It must not be used to justify a Host zero. |
| 7. Business web preview | **Affected and deployment-proven.** Current Host web bundle contains the exact crash and masking branches. |

Adjacent shared consumers found by exhaustive call-site search: event Orders list (explicit “Couldn't load orders”), event dashboard/tier sold counts, guest list/detail (empty fallback), reconciliation, `useEventHasWebPurchases`, experience detail and trip detail’s event-order branch. Any free zero-total order with null currency can poison the entire event’s fetch, not only Korede’s event. RSVP without monetary contributions normally has no order rows and therefore does not trigger this mapper; its attendee truth is the RSVP table, not `orders`.

### Multi-day ticket model note

The two 300-capacity ticket types are production configuration, not the reporting root cause. #2160’s multi-day model allows one ticket/pass to select multiple event dates through `ticket_event_dates`; it does **not** automatically decide whether admission inventory is “one shared pass across both days” or “a distinct day-specific product.” Two day-named tiers can be intentional if buyers choose a day, but `300 + 300` represents two separate sellable tier capacities rather than one automatically shared 300-per-day pool. That product/configuration question should be reviewed separately and must not be mixed into the proven order-read failure.

### Security and invariant findings

- **Architecture Constitution #2 — one owner per truth:** violated at the client boundary; schema truth is nullable while handwritten `OrderRow` says string.
- **#3 — no silent failures:** violated in editor/reconciliation/guest helper paths that discard `isError` and return `[]`.
- **#9 — no fabricated data:** violated by `soldCount:0` / empty sold context when the state is unknown due to error.
- **#10 — currency-aware everywhere**, `I-1014-FREE-PUBLISH-NO-PAYMENT-SETUP`, and `I-PROPOSED-962-NO-GBP-IN-PREBANK-MONEY-SURFACES`: database/writer honor them; the reader crashes rather than honoring null-as-no-currency. No currency fallback should be inferred from a bank workaround.
- RLS/authz and response containment were inspected. No cross-brand leak, overbroad anonymous read or hidden-field exposure caused by this defect was found. The nested buyer PII remains behind authenticated buyer/brand-team RLS.
- Server-side edit protections remain the final authority, limiting mutation-integrity risk from the editor’s blind client context; the organiser experience is still materially unsafe/misleading.

### Alternative hypotheses reconciled

1. **Missing bank/currency blocks free order creation** — disproven by the 3/6 production rows and #1014 contract.
2. **RLS hides Korede’s orders** — disproven by actual owner-UID RLS counts.
3. **PostgREST nested relationship/schema cache is broken** — disproven by exact HTTP 200 response with all joins.
4. **Free orders have an excluded status** — disproven; all are `paid`, the canonical finalized free status.
5. **A stale zero is cached** — disproven by fresh response replay; mapper always throws.
6. **#2402 already fixed this** — disproven by different mapper ownership and current deployed chunk.

### Confidence

**PROVEN / high confidence.** One production-data invariant, one live migration contract, one exact successful API response, one deterministic runtime exception, and the current deployed Host artifact all reconcile into the same causal chain across the three reported surfaces. The remaining uncertainty is limited to the separate product intent behind the two day-specific capacities, not the reporting defect.

### Recommended next phase and bounded scope

Route to orchestrator review, then a separate **SPEC** only after approval. The bounded next scope should cover the shared raw-order mapping contract for valid null-currency zero-total orders; honest loading/error/unknown handling for every direct `useEventOrders` / sales-summary / reconciliation consumer; and regression coverage that begins with raw database-shaped free-order rows and proves 3 orders / quantity 6 reach Host reporting. It should explicitly avoid database backfill, changing #1014’s null-currency invariant, requiring a bank, mutating Korede’s orders, changing checkout/finalizer behavior, or redesigning multi-day inventory. No fix, migration, deploy or product mutation was performed in this investigation.

**Comment by sethogieva** [comment]
## ORCHESTRATOR REVIEW — INVESTIGATION APPROVED

**Verdict: APPROVED.** The investigation proves one root cause across production schema/data, the exact successful PostgREST response, the deployed Host artifact, current source, and organiser-context RLS. Three valid zero-total orders legitimately carry `currency=NULL`; the shared Host mapper's handwritten non-null contract calls `.trim()` on that value, rejects the entire read, and downstream Home/Hub/editor consumers convert the error to `[]`/numeric zero.

### Review gates

- Root cause: proven, not merely plausible.
- Alternatives disproven: bank/payout onboarding, event completeness, RLS/membership, PostgREST joins/schema cache, payment status, stale cache, and #2396/#2402.
- Five truths reconciled: intended #1014 contract, live nullable schema/constraint, current writer/finalizer, production rows, and deployed reader/UI.
- Blast radius: all direct/shared Host order consumers mapped; buyer web is a successful upstream writer; consumer/admin exclusions are reasoned.
- Security: organiser RLS admits only authorized data; no weakening or data mutation is required.
- Scope: bounded to raw order mapping plus honest error/unknown propagation; no database backfill, checkout rewrite, bank requirement, customer-row mutation, or multi-day inventory redesign.

### Commit-hash verification

Investigation is documentation-only under Operating Model V2 and is stored in the issue comment; no repository files were changed or claimed. The reviewed source was verified against current `origin/main`, including `mingla-business/src/services/eventOrdersService.ts`, `src/hooks/useEventOrders.ts`, and `src/utils/eventSalesSummary.ts`; the investigation separately verified the currently deployed Host chunk.

### Dependency walk

No configuration-layer file changed, so the configuration dependency-walk trigger is N/A. The functional dependency walk is complete: `fetchEventOrders` → `useEventOrders` / `useEventSalesSummaries` → Home, Hub/EventListCard, event dashboard/editor, Orders, guest/reconciliation helpers, experience detail, and trip detail's event-order branch.

Advance to a separate binding SPEC. The SPEC must preserve null currency without fabrication for zero-total orders, fail closed for money-bearing orders with invalid currency, and prevent every affected consumer from presenting unknown/error as a truthful zero.

**Comment by sethogieva** [comment]
## ORCHESTRATOR REVIEW — SPEC APPROVED

**Verdict: APPROVED.** The SPEC binds the proven root cause to a truthful nullable-currency model, fail-closed money validation, and explicit non-ready states across every consumer of the poisoned shared order read. It is implementable without product decisions and preserves the correct database, checkout, RLS, query-key, cache-owner, and bank-independent contracts.

### Scope review

The allowlist is broader than the one-line mapper correction because the shared rejected query currently fans out into Home, Hub, dashboard/editor, orders, guests, reconciliation, experience/trip summaries, and purchase guards. The breadth is justified by Constitution rules against silent failures and fabricated zero; implementation must still subtract obsolete `data ?? []`/zero fallbacks rather than build a second state owner.

### Required gates confirmed

- All 11 SPEC sections, numbered success criteria, seven-surface declaration, state/error matrix, security/observability/accessibility, rollout and validation contracts are present.
- Free zero-money `currency=NULL` remains truthful; positive money/refunds with missing or mismatched currency fail closed with stable safe codes.
- Loading/error/stale-error cannot become zero/empty/false/not-found; only `ready` data reaches sold/revenue/edit guards.
- Exact implementor/tester additive regression files, fail-on-revert requirements, file allowlist, do-not-touch list and no-migration/no-bank/no-customer-mutation constraints are locked.
- Public Host OTA/build remains separately approval-gated by COMMS-0147.

### Commit-hash verification

SPEC is stored as an issue comment under Operating Model V2; no repository files were changed or claimed. The branch is clean and current with the reviewed `origin/main` baseline.

### Dependency walk

No configuration-layer file changes are specified, so the configuration dependency-walk trigger is N/A. Functional dependencies are explicitly traced from `fetchEventOrders` through the shared hooks, summaries, money/refund/activity/reconciliation helpers, and every affected Host route/component; buyer web compatibility is separately bounded and checkout remains untouched.

Advance to `mingla-implementor`. Any non-allowlisted file or contract change requires a SPEC amendment before implementation continues.
