### ISSUE TITLE
Address-privacy toggle is not enforced on one read path

### ISSUE THREAD

**Issue by sethogieva** [Mingla-LLC/mingla-main#2489]
## Summary

The **"Hide address until ticket purchase"** toggle is not fully enforced on one read path. A published event with the toggle on can expose location precision it promises to withhold, to readers who have not met the unlock condition.

The explorer enforces this correctly. The affected path is business / buyer-web.

## Severity

P0 — Trust & Safety. It breaks a privacy promise the product makes to hosts in writing, and it affects a small number of currently-published events.

## Root cause class

A client that trusts a documented server-side guarantee which was never implemented. One read path applies the gate correctly; a second does not, and the renderer on that path assumes it does. A code comment asserting an invariant is not enforcement.

## Fix shape

1. Enforce the gate at the **server boundary**, so no client can leak the value by accident and the three renderers cannot drift apart again.
2. Add a regression test asserting the unauthenticated payload carries no withheld precision for a gated event.
3. Audit the remaining read paths for the same assumption.
4. Verify the currently-affected published records after the fix lands.

## Provenance

Found by the adversarial tester during #2468. **Pre-existing; not introduced by #2468**, which changed map links rather than this path, and whose own privacy gate is correct. Kept out of that PR deliberately.

Full detail is with the orchestrator and will be supplied to whoever picks this up.

## Affected Surfaces
[buyer-web, business-iOS, business-Android]
Surfaces explicitly NOT in scope: iOS-consumer/Android-consumer (gated correctly), admin-web (authenticated staff surface).

**Comment by sethogieva** [comment]
## Implementation — rework pass, phase 1 of 2

Class-level only; the repository is public and the disclosure is not yet closed. Detail is
held locally with the orchestrator.

**This phase does not close the primary disclosure.** It ships everything that changes no
behaviour anyone depends on. The access change that actually closes it is a second,
coordinated deploy that follows once this one is live. Nobody should read a merge here as
the issue being resolved.

What the rework added on top of the first attempt, all of it found by the adversarial review:

- **A second door to the same value.** A field named for the venue rather than the address
  fell back, on three readers, to a stored string that contains both. So an offering could
  have its address correctly withheld and still ship it, through a field the gate never
  looked at. No record is in that state today; one ordinary publish creates one. The
  fallback now sits inside the gate.
- **The guard could not fail; the thing it guarded could.** On the two list readers that
  meant one malformed record answering an entire market's request with an error rather
  than one bad row. That projection is now a single total function.
- **"Defined once" was true of half the objects.** The rest re-implemented the rule inline
  in a form that errors on unexpected input. They all call the one definition now.
- **Two anonymous checkout resolvers** stopped asking the underlying record for fields they
  never read.

**On keeping the gate from being lost again.** For the objects that respect row-level
policy, enforcement belongs underneath the projections, where re-emitting a projection
cannot widen it and caller-rights readers are protected for free. For the readers that run
with elevated rights no such protection exists — they bypass policy by construction — so
for those, detection is the only defence and it is built accordingly: a pinned set of the
objects required to carry the gate, compared for equality in both directions against what
the catalogue actually references, evaluated at the end of a full in-order replay, and
refusing to pass if a declared object is missing so it cannot succeed by finding nothing.
That distinction is stated plainly rather than papered over.

**On the tests being able to fail.** Per the concern raised on a peer issue, presence of an
assertion is not evidence it runs. Two additions: a permanent negative control that stages a
real violation and requires the suite to catch it, and a ledger that fails the run if any
scenario stopped executing. A privacy suite that quietly stops asserting still reports green,
and that green then vouches for the hole.

Verified on a disposable local cluster replaying the full chain in order. Fails-on-revert
proven in both directions. No deploy, no migration applied, no production write.

Two findings for separate triage were recorded locally, including one that would have made
the follow-on access change a silent no-op.

Next: tester.

**Comment by sethogieva** [comment]
## Phase 2 — the base record is closed to anonymous callers

Branch `2489-phase2-base-revoke`. Class-level by design: the repository is public and this is a live privacy hole until the migration is applied. No record, coordinate, address, schema object, column, grant, origin or runnable query appears below.

**Not deployed.** Migration written, not applied. Production migration history has drifted, so `supabase db push` stays forbidden — this file's SQL alone, then only its history row.

### The correction that mattered

The fix was specified as a **column-level revoke**. That form is a **no-op** while the role still holds a table-level grant, and it is a no-op *silently* — it applies, exits zero, passes review, and changes nothing. Verified in both directions on a disposable cluster before anything was written.

Shipped as specified, it would have closed this issue on paper and left the disclosure exactly where it was.

The shape actually implemented is: **remove the table-level grant, then grant back only the columns anonymous consumers are proven to need**, derived from the catalog rather than typed out, with a vacuity guard that refuses to apply if the exception list ever stops naming real columns.

### What that shape breaks — handled before the grant moves, not after

A **caller-rights view fails entirely** when its *body* reads a withheld column, even when the caller's own query never projects it. Two anonymous-readable caller-rights views over this relation do exactly that, and both would have gone dark the instant the grant changed. They are handled on opposite merits rather than with one blanket rule: one is already gated and its own row filter is a strict subset of the policy it would stop inheriting, so it takes owner rights; the other has no row filter and no gate, so owner rights there would have been a far worse leak — its anonymous grant is withdrawn instead, and it had no anonymous caller to lose.

Every consumer was re-derived from scratch rather than taken from the prior investigation. Both figures in that investigation were wrong in the safe direction, and one object it described as caller-rights is in fact owner-rights — which is why the front door survives this untouched.

### Deliberately not closed

One column stays readable, and with it one of the three disclosure vectors. Two live anonymous revenue routes read that column and no gated object can serve them a substitute without withholding something that is legitimately public for their offering kind. Closing it needs new anonymous read surface — its own design, its own tests, its own deploy.

**So this closes two of the three vectors against unauthenticated callers, and the third only on the derived paths.** The scope limit is asserted in the fixture and written into the invariant rather than left implied, so it cannot quietly be read as "address privacy enforced". The separate residual for signed-in non-members is unchanged and still tracked.

### Evidence

Sixteen behavioural scenarios, every read performed as an unauthenticated caller against a fully replayed chain on a throwaway cluster.

- Both vectors closed: projection **and** filtering, the latter across four distinct reference shapes, plus whole-row reads and reads reached through a child table.
- **Four anti-vacuity scenarios** re-run the two live anonymous resolvers' exact column lists and ordinary browsing, so a grant set that closes the hole by closing the product fails instead of passing.
- **Two negative controls.** The second is the one the file exists for: it stages the no-op form inside a savepoint and requires the unauthenticated read to *still succeed*. The reason the migration has the shape it has is now proven in the suite, not argued in a comment.
- Phase 1's own dormant assertions arm on this change and pass. Its adversarial suite stays green — including the one assertion that would have caught the view breakage, which is what the owner-rights flip is for.
- A fixture fault was found and fixed mid-build: four refusals were initially passing for the wrong reason. Every refusal now proves *what* refused it.
- Fails on revert by true line deletion: the migration's own post-apply check aborts naming the no-op, and the fixture raises on its first assertion. Restored byte-identical; the full chain re-applies clean.

Registered in the existing provider suite. One filtered replay lane needed the new migration on its skip list, by exact filename, for a conflict that was **reproduced before the entry was added and confirmed clean after**; a second lane was simulated with this change present and needs no entry. Counts only in the closure gate and its fixtures, under an approved-modification token — no assertion, parser case or mutation scenario changed.

### Next

Review, then apply this migration's SQL alone and its history row alone. Verify by re-reading the grants and the view setting afterwards — a deploy command's exit code is not evidence.
