### ISSUE TITLE
Dev server cannot resolve any dynamic import() in a spawned worktree — runtime testing blocked

### ISSUE THREAD

**Issue by sethogieva** [Mingla-LLC/mingla-main#1544]
Found during #1532 testing (2026-08-04). Sibling of #1492 — **different root cause, same consequence**: runtime verification in a worktree costs a tester hours it should not.

## What happens

In a worktree spawned by `scripts/orch-worktree/spawn.sh`, every dynamic `import()` fails against the dev server:

```
Unable to resolve module ./mingla-main/mingla-business/node_modules/…
```

Observed during #1532 testing:

- red-screened the reserve sheet on the first iOS attempt
- blocked pointer events on dev web
- **survived `--clear` and a watchman reset**

`npx expo export -p web` from the same worktree is completely clean. So this is the dev server only — but the dev server is where all runtime testing happens.

## Hypothesis, stated as a hypothesis

`spawn.sh` names worktrees `~/Desktop/mingla-orchs/<issue>-[<label>]` — **with literal square brackets**. Brackets are glob/character-class metacharacters, and several layers here do path matching (Metro's resolver and `blockList`/`watchFolders`, watchman, `node_modules` symlink traversal). The resolved path in the error is also relative-looking (`./mingla-main/…`) rather than absolute, which is what a mangled path prefix would produce.

I have **not** proven this. It is the obvious suspect and it has a cheap experiment.

## The cheap experiment

Existing worktrees are split on this, so no new setup is needed:

- bracketed: `1532-[stay-manager-ux]`, `1481-[explorer-swipe-hang]`, `1367-[claimed-venue-discovery-links]`
- unbracketed: `1365-brand-reservations-design`, `1401-fee-preview-bank-payout`, `1430-independent-test-clean`

Start the dev server in one of each and hit any route with a lazy import. If the unbracketed one resolves and the bracketed one does not, the cause is the brackets and the fix is one line in `spawn.sh` — plus a migration note, since every live worktree would need renaming.

If brackets are **not** the cause, the next suspects are the `node_modules` symlink (spawn symlinks rather than installs) interacting with Metro's `watchFolders`, and whether the anchor's absolute path leaks into a cached resolver map.

## Why this is worth fixing rather than working around

Standing policy is that a control wired in source is not proven until it fires at runtime, and #1484 is the case study for why: 29 headless tests passed while the feature was visibly broken in a browser. If reaching a runtime at all requires undocumented per-session improvisation, verdicts quietly drift back toward headless-only — which is the exact failure mode the runtime rule exists to stop.

Two blockers now stand between a tester and a running app in a fresh worktree: this and #1492. Both were hit on #1532.

**Affected Surfaces:** business-iOS, business-Android, business-web-preview, consumer iOS/Android (any worktree-based runtime test) — tooling, not shipped product.
**Surfaces explicitly NOT in scope:** production builds — `expo export` is verified clean.

**Comment by sethogieva** [comment]
## Additional runtime evidence from #3430

Issue #3430 independently reproduced the existing residual RSVP lazy-chunk failure on the current `origin/main` code path even after real `npm ci`; the RSVP lazy-module owner was byte-identical between the branch and main (SHA-256 `13e121b6e83bcea8f1c09e0c8f96ab1362268b155c7c04f52a5ecfafcae22c57`). Business Metro web preview and Host Android dev-client lazy loading hit the same `./packages/offering-rendering/RsvpGoingConfirmDialog` shape.

The evidence also reconfirms the scope boundary: the exact production web export emitted and loaded the RSVP chunk with zero console errors, and Host Android rendered the full RSVP destination under Expo's supported `EXPO_NO_METRO_LAZY=1` eager mode. This is therefore still a dev Metro/runtime-testing defect, not a shipped production defect and not caused by #3430. The full QA matrix is in https://github.com/Mingla-LLC/mingla-main/issues/3430#issuecomment-5685789663.
